# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94121fa8fe39c9c52b8cc9b8b2bbdac2747c4499b8bdf71c76c58c362716671bf8ade4cf9e36f94cb0bfa4af1c5b58fe621479175677f8c461bb9ed1caa2b049

test:
  secret_key_base: 9a474ad12abbf6ceb31dd478ee464a481c6307dadef901366eed3247412457094060ee1465c9db7d0bd59740fd22c81c8d56ce28d2e6560cf90eb68be124fab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
